src/js/gallery.js

literoweczka-feTch

---

src/partials/example.html
src/partials/footer.html
src/partials/header-library.html
src/partials/header.html

rename tags articles - sections

---

src/index.js
src/js/header.js
src/sass/_header.scss
src/sass/main.scss

dodałem jeszcze header na scrolla może będzie odpowiedni

added fixed header

---

src/sass/_gallery.scss
src/sass/main.scss

gallery styling refactored

---

src/partials/header.html
src/sass/_header.scss

poprawiłem widok obrazu headera

debuged background-image

---

src/index.js
src/js/renderMovies.js
src/partials/modal.html
src/sass/_modal.scss

wersja beta modala na mobilne urządzenia

modal wersja mobilna

---

src/js/header.js
src/partials/header-library.html
src/partials/header.html
src/sass/_header.scss
src/sass/main.scss
src/sass/partials/_btn.scss

little bugfix

---

src/index.html
src/js/renderMovies.js
src/sass/_modal.scss

tylko jeszcze będę musiała coś zaradzić na te ucięte plakaty

mobilka skończona

---

src/js/fetchMovies.js
src/js/gallery.js
src/js/header.js
src/js/renderMovies.js
src/partials/gallery.html

pagination

---

src/js/renderMovies.js
src/sass/_gallery.scss

dodanie if'a gdy brakuje movie postera w bazie danych.
polerka kodu, wyrównanie boxów "do góry" w razie gdyby movie poster był mniejszy

adding "if image is null"

---

src/js/renderMovies.js
src/sass/_header.scss
src/sass/_modal.scss

pozostaje jeszcze zrobić tak by modal zamykał się gdy kliknie się na background ale to już później bo padam

zmiany w modalu plus gotowy modal

---

src/js/header.js
src/partials/header-library.html
src/partials/header.html
src/sass/_header.scss
src/sass/main.scss

dodałem background na header na sztywno w miarę możliwości,
a w drugim commice dodałem tylko od 1280px na sztywno reszta na width:100%

change header

---

src/sass/_footer.scss
src/sass/main.scss

zmieniłem footera by był podobny szerokością do headera.

added to footer @medai, change width

---

src/partials/header-library.html
src/sass/_gallery.scss
src/sass/_header.scss
src/sass/partials/_btn.scss

dodałem media do galerii by wyrównać w miarę możliwości odstęp miedzy galerią a headerem

added media

---

src/js/header.js
src/sass/_header.scss
src/sass/main.scss

został zmieniony header odnośnie scrolla

rebuild header

---

src/sass/_footer.scss
src/sass/_header.scss

remove padding in header and footer

---

src/js/modal.js
src/sass/_modal.scss

hej poprawiłam scroll, eventlistener na escape i zamykanie a klikania w background.

modal poprawki zrobione

---

src/js/modal.js

hej, musiałam poprawić kod by modal zamykał się tylko z kliknięcia na background (poprzednio zamykał się również z kliknięcia w modal).

Modal final adjustments

---

src/js/renderMovies.js
src/partials/gallery.html

maly bugfix z rana jak smietana :P

if date and genres not provided

---

src/index.html
src/js/fetchMovies.js
src/js/header.js
src/my-library.html
src/sass/_header.scss

Dodatkowo dodano favicon (to samo co w logo)
Parę zmian w header (opóźnienie animacji, pomniejsze pierdoły)

Naprawiono funkcję fetchID

---

src/js/genres.js
src/js/makeMoviePoster.js
src/js/modal.js
src/js/renderMovies.js

podwojny kod, ktory generowal plakaty i genres w galerii i modalu wywalilem do osobnych funkcji w osobnych plikach i odpowiednio sa teraz importowane

makeGenres + makePosters

---

src/js/library.js
src/js/modal.js
src/js/reloadLibrary.js
src/partials/header-library.html
src/partials/header.html
src/partials/library.html
src/sass/main.scss

Naprawione usuwanie filmów z watched i queue.

fixed remove from library

---

src/partials/modal-team.html
src/sass/_modal-team.scss

changes on branch social-media

---

src/js/gallery.js
src/js/library.js
src/js/refs.js
src/partials/library.html

pagination-library

---

src/js/gallery.js
src/js/library.js
src/js/refs.js
src/partials/library.html

Reverts WiktorRLewandowski/projekt-grupa-3#71

Revert "pagination-library"
